# This is a basic workflow to help you get started with Actions

name: Test code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "test"
  test:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A strategy creates a build matrix for your jobs
    strategy:

      # You can define a matrix of different job configurations
      matrix:

        # Each option you define in the matrix has a key and value
        python-version: [ 3.8 ]

    steps:
       - uses: actions/checkout@v3
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip wheel setuptools
           python -m pip install -r requirements.txt
           python -m pip list
       - name: Test with pytest
         run: |
           python ./scripts/run_tests.py
